name: CI for topojson-schema

on:
  pull_request:
    paths:
      - packages/topojson-tests/**
      - packages/topojson-schema/**
  push:
    branches:
      - main
    paths:
      - packages/topojson-tests/**
      - packages/topojson-schema/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build topojson-schema
        working-directory: ./packages/topojson-schema
        run: bun run build
      - name: Run tests on topojson-schema build output
        working-directory: ./packages/topojson-schema
        run: bun run test
