name: CI for topojson-valibot

on:
  pull_request:
    paths:
      - packages/topojson-tests
      - packages/topojson-valibot
  push:
    branches:
      - main
    paths:
      - packages/topojson-tests
      - packages/topojson-valibot
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run tests for topojson-valibot
        working-directory: ./packages/topojson-valibot
        run: bun run test
